package com.omarfraser.bugtrail.domain;

import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.Objects;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

/**
 * A reported defect, and the record of everything that happened to it.
 *
 * <p>The central entity of BugTrail. Two things about it are worth knowing before
 * reading the fields:
 *
 * <p><b>Severity and priority are separate.</b> Severity describes the defect and
 * is set by the reporter. Priority describes the schedule and is computed by
 * {@code TriageService}. They routinely disagree, and collapsing them into one
 * field is the most common modelling mistake in home-grown bug trackers.
 *
 * <p><b>Status changes go through {@code TransitionValidator}.</b> Setting the
 * status field directly bypasses the workflow rules, so the only supported route
 * is the service layer.
 */
@Entity
@Table(name = "ticket")
public class Ticket {

    /**
     * Surrogate primary key, generated by the database.
     *
     * <p>Never shown to a user and never used in {@code equals} -- see
     * {@code reference} for the identifier people actually work with.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Human-readable key, e.g. {@code BT-142}. Assigned once, never reused,
     * even if the ticket is deleted.
     *
     * <p>This is what people say out loud, paste into commit messages, and search
     * for. The numeric id exists for the database; this exists for humans.
     */
    @Column(name = "reference", nullable = false, unique = true, length = 24)
    private String reference;

    /**
     * The project the defect was filed against. Never null -- a ticket outside a
     * project has no component list, no reference prefix, and nobody to triage it.
     *
     * <p>LAZY like every association here. Loading a ticket should not drag its
     * project, and everything hanging off that project, into memory for a caller
     * that only wanted the title.
     */
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "project_id", nullable = false)
    private Project project;

    /**
     * The component the defect is in. Nullable, because a reporter often does not
     * know -- "the app crashed" does not tell you whether it was auth or the board.
     * Triage assigns it, which is also when it starts affecting the priority score.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "component_id")
    private Component component;

    @Column(name = "title", nullable = false, length = 255)
    private String title;

    @Column(name = "description", nullable = false, columnDefinition = "text")
    private String description;

    /**
     * Numbered steps that reproduce the defect. Nullable, but a report without
     * them is usually the one that gets bounced back -- "it's broken" is not
     * actionable, and the round trip to ask costs more than writing them did.
     */
    @Column(name = "steps_to_reproduce", columnDefinition = "text")
    private String stepsToReproduce;

    /**
     * Browser, OS, app version, device. What distinguishes "it's broken" from
     * "it's broken on Safari 17".
     */
    @Column(name = "environment", length = 255)
    private String environment;

    /**
     * Current position in the workflow.
     *
     * <p>Defaults to NEW, mirroring the column default. There is deliberately no
     * public setter -- see {@code transitionTo} further down. Every change has to
     * pass {@code TransitionValidator}, and a setter would be a way around it.
     */
    @Enumerated(EnumType.STRING)
    @Column(name = "status", nullable = false, length = 16)
    private TicketStatus status = TicketStatus.NEW;

    @Enumerated(EnumType.STRING)
    @Column(name = "severity", nullable = false, length = 16)
    private Severity severity;

    @Enumerated(EnumType.STRING)
    @Column(name = "reproducibility", nullable = false, length = 16)
    private Reproducibility reproducibility;

    /**
     * Whether this worked in a previous release. Weighted heavily in triage --
     * a regression means the test suite failed to catch something it should have.
     */
    @Column(name = "is_regression", nullable = false)
    private boolean isRegression = false;

    /**
     * Proportion of users affected, 0.0000 to 1.0000.
     *
     * <p>BigDecimal, not double, because the column is NUMERIC(5,4) -- an exact
     * decimal type. Starts at zero: nobody knows the reach of a defect when it
     * is first filed.
     */
    @Column(name = "affected_user_fraction", nullable = false, precision = 5, scale = 4)
    private BigDecimal affectedUserFraction = BigDecimal.ZERO;

    /**
     * Computed by {@code TriageService}, never set by the reporter.
     *
     * <p>Nullable because a ticket has no priority until it is triaged -- NEW
     * tickets carry a null here, and that is meaningful rather than missing data.
     */
    @Enumerated(EnumType.STRING)
    @Column(name = "priority", length = 4)
    private Priority priority;

    /**
     * The raw weighted score behind the priority bucket, 0.00 to 100.00.
     *
     * <p>Stored alongside the bucket so triage decisions can be explained after
     * the fact -- "why is this P1" is answerable with a number, and re-tuning the
     * weights later can be evaluated against historical scores.
     */
    @Column(name = "triage_score", precision = 5, scale = 2)
    private BigDecimal triageScore;

    /**
     * True when the P0 floor rule overrode the computed bucket: a BLOCKER on a
     * CRITICAL_PATH component is always P0, whatever the arithmetic said.
     *
     * <p>Surfaced rather than hidden so the UI can explain to a developer why a
     * mid-scoring ticket is sitting at the top of their queue.
     */
    @Column(name = "floored_to_p0", nullable = false)
    private boolean flooredToP0 = false;

    /**
     * A QA lead's manual override of the computed priority.
     *
     * <p>Null in the normal case. When set, all four override fields below must be
     * populated together -- the {@code ticket_override_needs_reason} constraint in
     * V1__init.sql enforces it at database level, so a partial override cannot
     * be written even by a buggy service or a manual UPDATE.
     */
    @Enumerated(EnumType.STRING)
    @Column(name = "priority_override", length = 4)
    private Priority priorityOverride;

    /**
     * Why the computed priority was wrong. Required whenever an override is set.
     *
     * <p>This is what makes the override auditable rather than arbitrary. "P2 but
     * the customer escalated to the CEO" is a reason; silence is not.
     */
    @Column(name = "priority_override_reason", columnDefinition = "text")
    private String priorityOverrideReason;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "priority_override_by")
    private AppUser priorityOverrideBy;

    @Column(name = "priority_override_at")
    private OffsetDateTime priorityOverrideAt;

    /**
     * Who filed it. Never null, never changes -- the reporter is a historical fact
     * about the ticket, and reassigning it would falsify the record.
     */
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "reporter_id", nullable = false)
    private AppUser reporter;

    /**
     * Who is working on it. Null until the ticket is assigned, and null again if
     * it goes back to the triage queue.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "assignee_id")
    private AppUser assignee;

    /**
     * The ticket this one duplicates, when status is DUPLICATE.
     *
     * <p>A self-reference: Ticket pointing at Ticket. The link is what lets the
     * board answer "how many people hit this", which then feeds the reach input on
     * the original's triage score -- five duplicates means five times the evidence
     * that it matters.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "duplicate_of_id")
    private Ticket duplicateOf;

    /**
     * How many times this ticket has been reopened.
     *
     * <p>A quality signal in its own right. A ticket reopened three times means
     * the fix was wrong twice, and that pattern is worth surfacing in the phase 5
     * analytics -- reopen rate says more about a team than raw close counts do.
     */
    @Column(name = "reopen_count", nullable = false)
    private int reopenCount = 0;

    @Column(name = "created_at", nullable = false)
    private OffsetDateTime createdAt = OffsetDateTime.now();

    /**
     * Last modification. Maintained by {@code touch()} rather than by the
     * database, so every write path goes through one place.
     */
    @Column(name = "updated_at", nullable = false)
    private OffsetDateTime updatedAt = OffsetDateTime.now();

    /**
     * When the ticket reached CLOSED. Null while open, and null again if it is
     * reopened.
     *
     * <p>This is the field mean-time-to-resolution is calculated from in phase 5:
     * {@code closedAt - createdAt}, bucketed by priority.
     */
    @Column(name = "closed_at")
    private OffsetDateTime closedAt;

    /**
     * Required by JPA. Application code should use the constructor below.
     */
    protected Ticket() {
    }

    /**
     * Creates a newly filed ticket.
     *
     * <p>The parameter list is deliberately the minimum that must be true for a
     * ticket to exist. Everything else is either defaulted or assigned later by
     * triage and the workflow -- a field that can be filled in afterwards does not
     * belong in a constructor.
     *
     * @param reference       human-readable key, assigned by the service layer
     * @param project         the project the defect was filed against
     * @param title           one-line summary, as the reporter wrote it
     * @param description     what happened, in full
     * @param severity        how badly the software misbehaves, set by the reporter
     * @param reproducibility how reliably the defect can be triggered again
     * @param reporter        who filed it
     */
    public Ticket(String reference,
                  Project project,
                  String title,
                  String description,
                  Severity severity,
                  Reproducibility reproducibility,
                  AppUser reporter) {
        this.reference = reference;
        this.project = project;
        this.title = title;
        this.description = description;
        this.severity = severity;
        this.reproducibility = reproducibility;
        this.reporter = reporter;


    }

     // ------------------------------------------------------------------
    // Accessors
    // ------------------------------------------------------------------

    public Long getId(){
        return id;
    }

    public String getReference(){
        return reference;
    }

    public Project getProject(){
        return project;
    }

    public Component getComponent(){
        return component;
    }

    public String getTitle(){
        return title;
    }

    public String getDescription(){
        return description;
    }

    public String getStepsToReproduce(){
        return stepsToReproduce;
    }

    public String getEnvironment(){
        return environment;
    }

    public TicketStatus getStatus(){
        return status;
    }

    public Severity getSeverity() {
        return severity;
    }

    public Reproducibility getReproducibility() {
        return reproducibility;
    }

    public boolean isRegression() {
        return isRegression;
    }

    public BigDecimal getAffectedUserFraction() {
        return affectedUserFraction;
    }

    public Priority getPriority() {
        return priority;
    }

    public BigDecimal getTriageScore() {
        return triageScore;
    }

    public boolean isFlooredToP0() {
        return flooredToP0;
    }

    public Priority getPriorityOverride() {
        return priorityOverride;
    }

      public String getPriorityOverrideReason() {
        return priorityOverrideReason;
    }

    public AppUser getPriorityOverrideBy() {
        return priorityOverrideBy;
    }

    public OffsetDateTime getPriorityOverrideAt() {
        return priorityOverrideAt;
    }

    public AppUser getReporter() {
        return reporter;
    }

    public AppUser getAssignee() {
        return assignee;
    }

    public Ticket getDuplicateOf() {
        return duplicateOf;
    }

    public int getReopenCount() {
        return reopenCount;
    }

    public OffsetDateTime getCreatedAt() {
        return createdAt;
    }

    public OffsetDateTime getUpdatedAt() {
        return updatedAt;
    }

    public OffsetDateTime getClosedAt() {
        return closedAt;
    }

    /**
     * The priority that actually applies: a QA lead's override when one exists,
     * otherwise the computed value.
     *
     * <p>Callers should use this rather than {@link #getPriority()}. Reading the
     * computed priority directly is how an override gets silently ignored.
     */
    public Priority getEffectivePriority() {
        return priorityOverride != null ? priorityOverride : priority;
    }
        // ------------------------------------------------------------------
    // Mutators
    //
    // Five fields out of twenty-seven get a setter. A public setter is a
    // promise that a field may change on its own, at any moment, with no rule
    // checked and nobody notified. Most of what a Ticket knows cannot honestly
    // make that promise, so most of it is changed through named operations
    // instead. See the note below for what was left out and why.
    // ------------------------------------------------------------------

    /**
     * Corrects the one-line summary.
     *
     * <p>Titles are rewritten constantly as understanding improves: "app
     * crashes" becomes "NPE in ReportExporter when the date range is empty"
     * once somebody reads the stack trace. That is editing, not a workflow
     * event, so it needs no rule.
     *
     * @throws NullPointerException if {@code title} is null
     */
    public void setTitle(String title) {
        this.title = Objects.requireNonNull(title, "title must not be null");
        touch();
    }

    /**
     * Replaces the full description.
     *
     * @throws NullPointerException if {@code description} is null
     */
    public void setDescription(String description) {
        this.description = Objects.requireNonNull(description, "description must not be null");
        touch();
    }

    /**
     * Sets or clears the reproduction steps. Null is allowed: plenty of tickets
     * are filed without them, and clearing wrong steps beats keeping them.
     */
    public void setStepsToReproduce(String stepsToReproduce) {
        this.stepsToReproduce = stepsToReproduce;
        touch();
    }

    /**
     * Sets or clears the environment string. Null is allowed for the same
     * reason as the steps above.
     */
    public void setEnvironment(String environment) {
        this.environment = environment;
        touch();
    }

    /**
     * Assigns or clears the component the defect lives in. Usually done during
     * triage, but also whenever somebody realises it was filed against the
     * wrong part of the system.
     *
     * <p>Note that component criticality is one of the five triage inputs, so
     * changing it after triage leaves {@code triageScore} describing a
     * component that is no longer this ticket's. Re-run triage after calling
     * this. That coupling is a known sharp edge, written down here rather than
     * discovered later.
     */
    public void setComponent(Component component) {
        this.component = component;
        touch();
    }

    /**
     * Records that something about this ticket changed.
     *
     * <p>Called by every mutator above rather than left to the caller. A caller
     * that must remember to update a timestamp is a caller that will forget,
     * and a stale {@code updated_at} fails silently -- nothing throws, the
     * ticket simply stops showing up in "changed since" queries.
     */
    private void touch() {
        this.updatedAt = OffsetDateTime.now();
    }


}
